import PDFDocument from "pdfkit";

// Client logo (also used as the watermark). Move to an env var if you prefer.
const LOGO_URL = "https://res.cloudinary.com/zs5iyswh/image/upload/v1786101871/vedant-solutions-logo_pjqkb0.png";

// ---- palette ----
const BRAND = "#1d4ed8";
const INK = "#0f172a";
const MUTED = "#64748b";
const LINE = "#e2e8f0";
const ZEBRA = "#f8fafc";

const CHANCE = {
  SAFE: { label: "Safe", color: "#16a34a" },
  MODERATE: { label: "Moderate", color: "#d97706" },
  RISKY: { label: "Risky", color: "#dc2626" },
};
const chanceOf = (c) => CHANCE[c] ?? { label: "—", color: MUTED };

const clean = (v) => {
  const s = (v ?? "").toString().trim();
  return !s || s.toLowerCase() === "data required" ? "NA" : s;
};
// PDFKit's built-in Helvetica has no ₹ glyph, so we use "Rs." here.
const feesText = (n) => (n && Number(n) > 0 ? `Rs. ${Number(n).toLocaleString("en-IN")}` : "NA");
const seatsText = (n) => (n && Number(n) > 0 ? String(n) : "NA");

// Cache the logo buffer across exports (retries on failure).
let cachedLogo = null;
async function loadLogo() {
  if (cachedLogo) return cachedLogo;
  try {
    const res = await fetch(LOGO_URL);
    if (!res.ok) return null;
    cachedLogo = Buffer.from(await res.arrayBuffer());
    return cachedLogo;
  } catch {
    return null;
  }
}

/**
 * Builds the Choice List PDF (async — fetches the logo). Returns a PDFDocument
 * with all content written but NOT ended; caller pipes it and calls doc.end().
 */
export const buildChoiceListPdf = async ({ choiceList, items = [], studentAIR }) => {
  const logo = await loadLogo();

  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const contentW = right - left;
  const pageBottom = doc.page.height - 46;

  // 22+168+70+60+58+78+59 = 515 = contentW
  const cols = [
    { key: "idx", label: "#", w: 22, align: "left", wrap: false },
    { key: "college", label: "College", w: 168, align: "left", wrap: true },
    { key: "state", label: "State", w: 70, align: "left", wrap: false },
    { key: "type", label: "Type", w: 60, align: "left", wrap: false },
    { key: "chance", label: "Chance", w: 58, align: "left", wrap: false },
    { key: "fees", label: "Fees / yr", w: 78, align: "right", wrap: false },
    { key: "seats", label: "Seats", w: 59, align: "right", wrap: false },
  ];

  // Safe / Moderate / Risky counts
  const counts = items.reduce(
    (a, it) => {
      if (it.chance === "SAFE") a.safe++;
      else if (it.chance === "MODERATE") a.mod++;
      else if (it.chance === "RISKY") a.risk++;
      return a;
    },
    { safe: 0, mod: 0, risk: 0 },
  );

//   const drawWatermark = () => {
//     if (!logo) return;
//     const w = 330;
//     doc.save();
//     doc.opacity(0.05);
//     doc.image(logo, (doc.page.width - w) / 2, (doc.page.height - w) / 2, { width: w });
//     doc.opacity(1);
//     doc.restore();
//   };

  const drawHeader = () => {
    if (logo) doc.image(logo, left, 26, { height: 34 });
    else doc.font("Helvetica-Bold").fontSize(18).fillColor(BRAND).text("Vedant Solutions", left, 30);
    doc.font("Helvetica-Bold").fontSize(11).fillColor(INK).text("Choice List", left, 34, { width: contentW, align: "right" });
    doc.moveTo(left, 72).lineTo(right, 72).lineWidth(1.5).strokeColor(BRAND).stroke();
  };

  const drawFooter = () => {
    doc.font("Helvetica").fontSize(8).fillColor(MUTED).text(
      "Generated by Vedant Solutions · Indicative only — verify on the official counselling portal.",
      left,
      doc.page.height - 32,
      { width: contentW, align: "center", lineBreak: false },
    );
  };

  const drawTableHeader = (y) => {
    doc.rect(left, y, contentW, 22).fill(BRAND);
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(9);
    let x = left;
    for (const c of cols) {
      doc.text(c.label, x + 5, y + 7, { width: c.w - 10, align: c.align, lineBreak: false });
      x += c.w;
    }
    return y + 22;
  };

  // ---- Page 1 ----
 // drawWatermark();
  drawHeader();

  let y = 86;
  doc.font("Helvetica-Bold").fontSize(14).fillColor(INK).text(clean(choiceList?.name), left, y, { width: contentW });
  y += 20;

  const generated = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  const metaLine = `Student AIR: ${studentAIR != null ? studentAIR : "NA"}    ·    Total Colleges: ${items.length}    ·    Generated: ${generated}`;
  doc.font("Helvetica").fontSize(9.5).fillColor(MUTED).text(metaLine, left, y, { width: contentW });
  y += 22;

  // summary chips
  const chips = [
    ["Safe", counts.safe, "#16a34a", "#dcfce7"],
    ["Moderate", counts.mod, "#d97706", "#fef3c7"],
    ["Risky", counts.risk, "#dc2626", "#fee2e2"],
  ];
  let cx = left;
  for (const [label, val, fg, bg] of chips) {
    const w = 110;
    doc.roundedRect(cx, y, w, 22, 6).fill(bg);
    doc.fillColor(fg).font("Helvetica-Bold").fontSize(9).text(`${label}: ${val}`, cx, y + 6, { width: w, align: "center" });
    cx += w + 8;
  }
  y += 34;

  y = drawTableHeader(y);

  if (!items.length) {
    doc.font("Helvetica").fontSize(10).fillColor(MUTED)
      .text("No colleges in this choice list yet.", left, y + 16, { width: contentW, align: "center" });
    drawFooter();
    return doc;
  }

  const collegeW = cols[1].w - 10;

  items.forEach((it, i) => {
    const college = clean(it.collegeId?.name);
    const nameH = doc.font("Helvetica-Bold").fontSize(8.5).heightOfString(college, { width: collegeW });
    const rowH = Math.max(24, nameH + 12);

    if (y + rowH > pageBottom) {
      drawFooter();
      doc.addPage();
      //drawWatermark();
      drawHeader();
      y = drawTableHeader(86);
    }

    if (i % 2 === 1) doc.rect(left, y, contentW, rowH).fill(ZEBRA);

    const ch = chanceOf(it.chance);
    const cells = [
      { text: String(i + 1), color: MUTED, bold: false },
      { text: college, color: INK, bold: true },
      { text: clean(it.collegeId?.state), color: MUTED, bold: false },
      { text: clean(it.collegeId?.ownership), color: MUTED, bold: false },
      { text: ch.label, color: ch.color, bold: true },
      { text: feesText(it.fees), color: MUTED, bold: false },
      { text: seatsText(it.seats), color: MUTED, bold: false },
    ];

    let x = left;
    cols.forEach((c, ci) => {
      const cell = cells[ci];
      doc
        .font(cell.bold ? "Helvetica-Bold" : "Helvetica")
        .fontSize(8.5)
        .fillColor(cell.color)
        .text(cell.text, x + 5, y + 6, { width: c.w - 10, align: c.align, lineBreak: c.wrap });
      x += c.w;
    });

    doc.moveTo(left, y + rowH).lineTo(right, y + rowH).lineWidth(0.5).strokeColor(LINE).stroke();
    y += rowH;
  });

  drawFooter();
  return doc;
};

export default buildChoiceListPdf;